[project]
name = "capability-registry"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
  "pydantic>=2.8",
  "motor>=3.5",
  "orjson>=3.10",
  "pika>=1.3",
]

[tool.uvicorn]
host = "0.0.0.0"
port = 8012
