[project]
name = "notification-service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.112",
  "uvicorn[standard]>=0.30",
  "aio-pika>=9.4",
  "pydantic>=2.8",
  "pydantic-settings>=2.3",
  "pyjwt>=2.8",
]

[tool.pytest.ini_options]
pythonpath = ["app"]
